apiVersion: apps/v1
kind: Deployment
metadata:
  name: nativeharvest-backend
  labels:
    {{- include "nativeharvest.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: nativeharvest-backend
  template:
    metadata:
      labels:
        app: nativeharvest-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: {{ .Values.backend.port }}
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: nativeharvest-secrets
                  key: jwtSecret
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: nativeharvest-secrets
                  key: dbHost
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: nativeharvest-secrets
                  key: dbName
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: nativeharvest-secrets
                  key: dbUser
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nativeharvest-secrets
                  key: dbPassword

