apiVersion: v1
kind: Secret
metadata:
  name: nativeharvest-secrets
type: Opaque
stringData:
  jwtSecret: {{ .Values.secrets.jwtSecret | quote }}
  dbHost: {{ .Values.secrets.db.host | quote }}
  dbName: {{ .Values.secrets.db.name | quote }}
  dbUser: {{ .Values.secrets.db.user | quote }}
  dbPassword: {{ .Values.secrets.db.password | quote }}

